"""Framework-independent Nexus job-domain contracts."""

from nexus_mcp.core.errors import InvalidJobTransitionError, NexusCoreError
from nexus_mcp.core.models import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    AccessContext,
    AccessPolicy,
    AgentSession,
    ApprovalPolicy,
    BackendEvent,
    ConfigLayerSnapshot,
    ConfigSource,
    ExecutionConfigValues,
    JobAttempt,
    JobEvent,
    JobEventType,
    JobPhase,
    JobState,
    ProviderReference,
    RequestedExecutionConfig,
    ResolvedExecutionConfig,
    RetryPolicy,
    SandboxMode,
    Workspace,
    WorkspaceSelector,
    new_id,
    validate_job_transition,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "TERMINAL_STATES",
    "AccessContext",
    "AccessPolicy",
    "AgentSession",
    "ApprovalPolicy",
    "BackendEvent",
    "ConfigLayerSnapshot",
    "ConfigSource",
    "ExecutionConfigValues",
    "InvalidJobTransitionError",
    "JobAttempt",
    "JobEvent",
    "JobEventType",
    "JobPhase",
    "JobState",
    "NexusCoreError",
    "ProviderReference",
    "RequestedExecutionConfig",
    "ResolvedExecutionConfig",
    "RetryPolicy",
    "SandboxMode",
    "Workspace",
    "WorkspaceSelector",
    "new_id",
    "validate_job_transition",
]
