"""Framework-independent job application and persistence contracts."""

from nexus_mcp.jobs.store import (
    CancelJobCommand,
    CancelledTerminalOutcome,
    ClaimedJob,
    ControlSnapshot,
    CreateJobCommand,
    CreateJobResult,
    EventPage,
    FailedTerminalOutcome,
    JobAccessFilter,
    JobQuery,
    JobStore,
    LeaseToken,
    PrunePolicy,
    PruneResult,
    ResolveInputCommand,
    RuntimeLease,
    RuntimeLeaseBusyError,
    StoredJobPage,
    SucceededTerminalOutcome,
    TerminalOutcome,
)

__all__ = [
    "CancelJobCommand",
    "CancelledTerminalOutcome",
    "ClaimedJob",
    "ControlSnapshot",
    "CreateJobCommand",
    "CreateJobResult",
    "EventPage",
    "FailedTerminalOutcome",
    "JobAccessFilter",
    "JobQuery",
    "JobStore",
    "LeaseToken",
    "PrunePolicy",
    "PruneResult",
    "ResolveInputCommand",
    "RuntimeLease",
    "RuntimeLeaseBusyError",
    "StoredJobPage",
    "SucceededTerminalOutcome",
    "TerminalOutcome",
]
