name: Pre-commit Autoupdate

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: pre-commit-autoupdate
  cancel-in-progress: true

jobs:
  autoupdate:
    permissions:
      contents: write
      pull-requests: write
    uses: j7an/shared-workflows/.github/workflows/pre-commit-autoupdate.yml@143198c39c5008b0a6a4d02a0f0218127db3d5e1 # v4.7.1
    secrets:
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
