name: Pre-commit Autoupdate

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: pre-commit-autoupdate
  cancel-in-progress: true

jobs:
  autoupdate:
    permissions:
      contents: write
      pull-requests: write
    uses: j7an/shared-workflows/.github/workflows/pre-commit-autoupdate.yml@798e12564a8aeacc4dda95f76d8d3d22d677f1a0 # v4.9.0
    secrets:
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
