name: Pre-commit Autoupdate

on:
  schedule:
    - cron: "0 8 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: pre-commit-autoupdate
  cancel-in-progress: true

jobs:
  autoupdate:
    permissions:
      contents: write
      pull-requests: write
    uses: j7an/shared-workflows/.github/workflows/pre-commit-autoupdate.yml@e22b38d70bf615d2e250718d430a5a4688fee158 # v4.2.3
    secrets:
      RELEASE_BOT_PRIVATE_KEY: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
